# Generated by Django 5.1.2 on 2024-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default='2005-01-20'),
            preserve_default=False,
        ),
    ]
